### ISSUE TITLE
To-dos

### ISSUE THREAD

**Issue by javirudolph** [javirudolph/montanaBats#2]
**Tasks in progress and to complete**

- [ ] Check that model fits are working and organize to one script
- [ ] Save model outputs to generate figures
- [ ] Edit estimation page on website to describe the three models
- [ ] Decide if I am making any model comparisons
- [ ] Visualize the coefficients for each of the model fits and compare
- [ ] write function to take those coefficients and simulate bat occupancy
